
version: v3.1

services:
  backend-app:
    depends_on:
      - mysqldb
    build: .
    ports:
      - 8080:8080
    environment:
      spring.datasource.url: "jdbc:mysql://mysqldb:3306/db_farmacia?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo&useSSl=false"
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: root

  mysqldb:
    image: mysql:9
    restart: always
    environment:
      MYSQL_DATABASE: db_farmacia
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306